"""add staff sessions and vehicle archiving

Revision ID: 44e9718a5560
Revises: f02478f83720
Created: 2026-09-27 14:59:26.812837

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "44e9718a5560"
down_revision: str | None = "f02478f83720"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_staff_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_sessions")),
    )
    op.create_index("ix_staff_sessions_expires_at", "staff_sessions", ["expires_at"], unique=False)
    op.create_index("ix_staff_sessions_token_hash", "staff_sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_staff_sessions_user_id"), "staff_sessions", ["user_id"], unique=False)
    op.add_column("vehicles", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        "ix_vehicles_active_created_at",
        "vehicles",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("archived_at IS NULL"),
        sqlite_where=sa.text("archived_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_vehicles_active_created_at",
        table_name="vehicles",
        postgresql_where=sa.text("archived_at IS NULL"),
        sqlite_where=sa.text("archived_at IS NULL"),
    )
    op.drop_column("vehicles", "archived_at")
    op.drop_index(op.f("ix_staff_sessions_user_id"), table_name="staff_sessions")
    op.drop_index("ix_staff_sessions_token_hash", table_name="staff_sessions")
    op.drop_index("ix_staff_sessions_expires_at", table_name="staff_sessions")
    op.drop_table("staff_sessions")
    # ### end Alembic commands ###
