"""create enquiries table

Revision ID: d5ab53f633ea
Revises: 44e9718a5560
Create Date: 2026-09-29 00:21:04.912750

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision = 'd5ab53f633ea'
down_revision = '44e9718a5560'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'enquiries',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            primary_key=True,
        ),
        sa.Column(
            'vehicle_id',
            sa.Uuid(),
            nullable=False,
            doc='Referenced vehicle',
        ),
        sa.Column(
            'customer_name',
            sa.String(200),
            nullable=False,
            doc='Full name of the enquirer',
        ),
        sa.Column(
            'customer_email',
            sa.String(320),
            nullable=False,
            doc='Email address of the enquirer',
        ),
        sa.Column(
            'customer_phone',
            sa.String(50),
            nullable=False,
            doc='Phone number of the enquirer',
        ),
        sa.Column(
            'message',
            sa.Text,
            nullable=False,
            doc='Enquiry message text',
        ),
        sa.Column(
            'status',
            sa.String(20),
            nullable=False,
            server_default='pending',
            doc='Enumerated: pending, answered, closed',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('now()'),
            doc='When the enquiry was submitted',
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('now()'),
            onupdate=sa.text('now()'),
            doc='When the enquiry was last updated',
        ),
        sa.Column(
            'vehicle_slug',
            sa.String(200),
            nullable=False,
            doc='Slug of the vehicle the enquiry is about',
        ),
        sa.ForeignKeyConstraint(
            ['vehicle_id'],
            ['vehicles.id'],
            name=op.f('fk_enquiries_vehicle_id_vehicles'),
            ondelete='CASCADE',
        ),
        sa.UniqueConstraint('vehicle_id', 'customer_email', name=op.f('uq_enquiries_vehicle_id_customer_email')),
        sa.CheckConstraint(
            "status IN ('pending', 'answered', 'closed')",
            name=op.f('ck_enquiries_status'),
        ),
    )
    op.create_index(
        op.f('ix_enquiries_vehicle_id'),
        'enquiries',
        ['vehicle_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enquiries_vehicle_id'), table_name='enquiries')
    op.drop_table('enquiries')
    # ### end Alembic commands ###