"""create vehicles tables

Revision ID: f02478f83720
Revises: 6a6b19f2de08
Created: 2026-09-27 13:36:48.908855

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f02478f83720"
down_revision: str | None = "6a6b19f2de08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("variant", sa.String(length=120), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("body_type", sa.String(length=60), nullable=True),
        sa.Column("transmission", sa.String(length=60), nullable=True),
        sa.Column("fuel", sa.String(length=60), nullable=True),
        sa.Column("colour", sa.String(length=60), nullable=True),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("vin", sa.String(length=17), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
        sa.Column(
            "availability",
            sa.String(length=16),
            server_default=sa.text("'available'"),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column(
            "features",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "availability IN ('available', 'reserved', 'sold')",
            name=op.f("ck_vehicles_availability"),
        ),
        sa.CheckConstraint("currency = 'USD'", name=op.f("ck_vehicles_usd_only")),
        sa.CheckConstraint(
            "mileage_km IS NULL OR mileage_km >= 0", name=op.f("ck_vehicles_non_negative_mileage")
        ),
        sa.CheckConstraint("price IS NULL OR price > 0", name=op.f("ck_vehicles_positive_price")),
        sa.CheckConstraint("vin IS NULL OR length(vin) = 17", name=op.f("ck_vehicles_vin_length")),
        sa.CheckConstraint("year >= 1900", name=op.f("ck_vehicles_plausible_year")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint("slug", name=op.f("uq_vehicles_slug")),
        sa.UniqueConstraint("vin", name=op.f("uq_vehicles_vin")),
    )
    op.create_index("ix_vehicles_created_at", "vehicles", ["created_at"], unique=False)
    op.create_table(
        "vehicle_images",
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("src", sa.String(length=2048), nullable=False),
        sa.Column("alt", sa.String(length=300), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("height > 0", name=op.f("ck_vehicle_images_positive_height")),
        sa.CheckConstraint("length(alt) > 0", name=op.f("ck_vehicle_images_alt_required")),
        sa.CheckConstraint("position >= 0", name=op.f("ck_vehicle_images_non_negative_position")),
        sa.CheckConstraint("width > 0", name=op.f("ck_vehicle_images_positive_width")),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_vehicle_images_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_images")),
        sa.UniqueConstraint("vehicle_id", "position", name="uq_vehicle_images_vehicle_position"),
    )
    op.create_index(
        op.f("ix_vehicle_images_vehicle_id"), "vehicle_images", ["vehicle_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vehicle_images_vehicle_id"), table_name="vehicle_images")
    op.drop_table("vehicle_images")
    op.drop_index("ix_vehicles_created_at", table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
